Scrap API
wafflestudio18-5/team7-server pull request #13
Opened 2021-01-04 05:29 UTC by shchoi94

2021-01-04 05:51 UTC, shchoi94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Scrap API](https://trello.com/c/VE2YJHkY/16-scrap-api)

2021-01-06 13:53 UTC, onemonster requested changes

2021-01-06 13:53 UTC, onemonster commented on written/posting/views.py
> +            rows[i]['title'] = Title.objects.get(pk=rows[i]['title']).name
N + 1 문제입니다. 위에서 JOIN을 통해 한번에 해결하셨으면 좋겠습니다.

2021-01-07 04:05 UTC, closed without merging

2021-01-07 04:06 UTC, shchoi94 commented
git conflict 가 생겨서..  닫고 새 브랜치 파서 작업