구독,구독취소[API Subscription] & error_code
wafflestudio18-5/team7-server pull request #5
Opened 2020-12-24 03:40 UTC by shchoi94

1. **_POST /users/{user_id}/subscribe/_** 와 
**_POST /users/{user_id}/unsubscribe/_**

2. **_written/error_codes.py_** 
아래처럼 사용하면 괜찮을 거 같아서
written/error_codes.py 를 작성해봤습니다. 어떤가요?
```
# 뷰 단
from written.error_codes import *
...
if writer is None:
    return Response(error_10003, status=status.HTTP_400_BAD_REQUEST)

# written/error_codes.py
...
error_10003 = {
    "errorcode": "10003",
    "message": "User does not exist"
}
```

2020-12-24 08:43 UTC, onemonster requested changes
error_XXXXX 이 방식 보단 Response를 상속해서 처리하는게 좋아보입니다. error_XXXXX는 이름만 보고 어떤 에러인지 몰라서 개발할 때 불편할 것 같습니다.

`return UserDoesNotExistResponse()`

이런식의 코드가 읽기 훨씬 쉽습니다. 그리고 장고를 잘 몰라서 그러는데 `throw`하는 방식은 없나요?

2020-12-24 08:43 UTC, onemonster commented on written/user/views.py
> +def get_subscription(subscriber_id, writer_id, sub_or_unsub):
메서드 이름은 get인데 create을 하기 때문에 부적절한 것 같습니다. get_or_create_subscription으로 바꾸던 생성 로직을 빼던 둘 중 하나는 해야합니다.

2020-12-24 08:43 UTC, onemonster commented on written/user/views.py
> +        if sb.is_active is False or sb is None:  # if False or None -> error
`sb is None`을 먼저 확인해야 하지 않나요? sb가 None이면 sb.is_active에서 터질것 같은데...

2020-12-24 10:28 UTC, shchoi94 commented on written/user/views.py
> +        if sb.is_active is False or sb is None:  # if False or None -> error
네 수정하도록 하겠습니다

2020-12-24 10:28 UTC, shchoi94 commented on written/user/views.py
> +def get_subscription(subscriber_id, writer_id, sub_or_unsub):
맞네요 감사합니다! create기능을 메소드에서 빼는 것으로 수정하겠습니다

2020-12-24 11:11 UTC, onemonster commented on written/written/error_codes.py
> +from rest_framework.response import Response
상속을 안 하는 구조 아닌가요 이렇게 하면?

2020-12-25 10:01 UTC, pullup-dip-burpee reviewed
LGTM  
views.py 먼저 개발하시고 models와 serializer는 그 뒤에 개발하시는 건가요?

2020-12-25 14:06 UTC, shchoi94 commented
@pullup-dip-burpee
보시면 subscription의  models.py 는 작성을 했습니다.ㅎㅎ
그리고 serializer는
 저희가 과제 할때 serializer 주로 사용해서  views.py를 작성할 때 serializer를 습관적으로? 당연하게? 사용하려고 보니까
너무 억지로 사용하는 감이 있더라고요. 
지금 [구독, 구독해제] api에 한해서는  input data, response body도 없어서 serializer 없이 구현하는게
더 간단하더라구요.
 그래서 일단 구독, 구독해제 api에 한해서는 serializer 없이 구현하였습니다.

2020-12-26 08:07 UTC, pullup-dip-burpee commented on written/subscription/models.py
> +    writer = models.ForeignKey(User, related_name='writer', on_delete=models.CASCADE)
이 부분 related name을  subscriber_subscription 등으로 수정하면 좋을듯합니다!

2020-12-26 08:26 UTC, onemonster approved these changes
LGTM

2020-12-26 08:26 UTC, onemonster commented
![](https://github.trello.services/images/mini-trello-icon.png) [Subscribe](https://trello.com/c/Y4SRbXx8/11-subscribe)

2020-12-26 08:27 UTC, merged