Facebook login/logout
wafflestudio18-5/team7-server pull request #6
Opened 2020-12-25 18:31 UTC by pasa3232

user api

2020-12-26 08:01 UTC, onemonster requested changes

2020-12-26 08:01 UTC, onemonster commented on requirement.md
> +django-allauth==0.44.0
이거 안 쓰는 거죠?

2020-12-26 08:01 UTC, onemonster commented on written/user/tests.py
> +                "access_token": "EAAEZAH2ttWo4BACPWqzJUxIyU1nrfyzv8JiZB7a3HJrDnqWDLRWofodYTN46rRS8PBZB4VxS469JPFTI3lNSXNJkGqA86QeKuZAuyygEfYNaostYWZA39Y8N0lKMrUMj2KKWJe01NbTGjxZB7cllZBg37FEfZBs20kBKD
https://www.20tab.com/en/blog/test-python-mocking/

테스트에서 access_token을 노출하지 않고 mocking을 하는게 좋을 것 같습니다

2020-12-26 08:01 UTC, onemonster commented on written/user/views.py
> +        url = f"https://graph.facebook.com/v7.0/me?access_token={access_token}"
facebook_client.py 같이 페북에 요청 보내는 클래스를 따로 만드시는걸 추천합니다.

2020-12-26 08:01 UTC, onemonster commented on written/user/views.py
> +        if response.status_code == status.HTTP_400_BAD_REQUEST:
페북 서버에 문제가 생기면 500에러도 뜰 수 있어서 200인지 아닌지로 하는게 더 좋을 것 같습니다.

2020-12-26 08:27 UTC, onemonster commented
![](https://github.trello.services/images/mini-trello-icon.png) [Facebook Login/Sign up](https://trello.com/c/ml7If2D3/5-facebook-login-sign-up)

2020-12-27 12:37 UTC, pasa3232 commented
피드백 모두 반영해서 push했습니다!
mocked_check_token 함수에선 `facebookid`와 `access_token`이 같을 때 validate하도록 처리했습니다.

2020-12-27 13:48 UTC, shchoi94 requested changes
코멘트 남겼습니다 확인 부탁드려요!

2020-12-27 13:48 UTC, shchoi94 commented on written/user/serializers.py
> +    def validate(self, data):
validate 정의 하신 이유가 따로 있나요?

2020-12-27 13:48 UTC, shchoi94 commented on written/written/error_codes.py
> +    error_code = "10003"
에러코드 string으로 바꾸셨는데
2개 에러만 int에서 string으로 바꾸셨네요!
pm님 의견으로도 int가 맞다고 하시더라구요

2020-12-28 06:07 UTC, pasa3232 commented on written/written/error_codes.py
> +    error_code = "10003"
앗 이것은 제 실수입니다. 감사합니다!
수정해서 push했어요

2020-12-28 06:09 UTC, pasa3232 commented on written/user/serializers.py
> +    def validate(self, data):
첨에 필요할거같아서 만들었다가 나중에 필요없어서 안쓴듯 합니다. 수정했습니다!

2020-12-28 06:17 UTC, shchoi94 approved these changes

2021-01-02 05:20 UTC, onemonster approved these changes
👍 LGTM

2021-01-02 05:20 UTC, merged